"""added background image

Revision ID: 146e78e8709c
Revises: 
Create Date: 2026-03-16 01:31:29.627911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146e78e8709c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', name='admin_role'), server_default='admin', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_club_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_users_is_active', 'admin_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_users_telegram_id'), 'admin_users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clubs_name', 'clubs', ['name'], unique=False)
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=True)
    op.create_table('djs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_djs_name', 'djs', ['name'], unique=False)
    op.create_index(op.f('ix_djs_telegram_id'), 'djs', ['telegram_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('notifications', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('admin_clubs',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id', 'club_id'),
    sa.UniqueConstraint('admin_id', 'club_id', name='uq_admin_club')
    )
    op.create_index('ix_admin_clubs_admin_id', 'admin_clubs', ['admin_id'], unique=False)
    op.create_index('ix_admin_clubs_club_id', 'admin_clubs', ['club_id'], unique=False)
    op.create_table('club_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('max_suggestions_per_user', sa.Integer(), server_default='3', nullable=False),
    sa.Column('voting_duration_sec', sa.Integer(), server_default='60', nullable=False),
    sa.Column('background_image_url', sa.String(length=1024), nullable=True),
    sa.Column('allow_explicit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_play', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_settings_club_id'), 'club_settings', ['club_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('preview', sa.String(length=2048), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'ended', name='event_status'), server_default='scheduled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_club_created', 'events', ['club_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_club_id'), 'events', ['club_id'], unique=False)
    op.create_index('ix_events_club_start', 'events', ['club_id', 'start_date'], unique=False)
    op.create_index('ix_events_club_status', 'events', ['club_id', 'status'], unique=False)
    op.create_index(op.f('ix_events_end_date'), 'events', ['end_date'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('event_djs',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('dj_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'dj_id'),
    sa.UniqueConstraint('event_id', 'dj_id', name='uq_event_dj')
    )
    op.create_index('ix_event_djs_dj', 'event_djs', ['dj_id'], unique=False)
    op.create_index('ix_event_djs_event', 'event_djs', ['event_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'number', name='uq_round_event_number')
    )
    op.create_index('ix_round_event', 'rounds', ['event_id'], unique=False)
    op.create_index('ix_round_event_number', 'rounds', ['event_id', 'number'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'title', 'artist', name='uq_song_round_title_artist')
    )
    op.create_index('ix_song_round', 'songs', ['round_id'], unique=False)
    op.create_index('ix_song_source_source_id', 'songs', ['source', 'source_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_vote_user_round')
    )
    op.create_index('ix_votes_round_song', 'votes', ['round_id', 'song_id'], unique=False)
    op.create_index('ix_votes_song_id', 'votes', ['song_id'], unique=False)
    op.create_index('ix_votes_user_round', 'votes', ['user_id', 'round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_user_round', table_name='votes')
    op.drop_index('ix_votes_song_id', table_name='votes')
    op.drop_index('ix_votes_round_song', table_name='votes')
    op.drop_table('votes')
    op.drop_index('ix_song_source_source_id', table_name='songs')
    op.drop_index('ix_song_round', table_name='songs')
    op.drop_table('songs')
    op.drop_index('ix_round_event_number', table_name='rounds')
    op.drop_index('ix_round_event', table_name='rounds')
    op.drop_table('rounds')
    op.drop_index('ix_event_djs_event', table_name='event_djs')
    op.drop_index('ix_event_djs_dj', table_name='event_djs')
    op.drop_table('event_djs')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_end_date'), table_name='events')
    op.drop_index('ix_events_club_status', table_name='events')
    op.drop_index('ix_events_club_start', table_name='events')
    op.drop_index(op.f('ix_events_club_id'), table_name='events')
    op.drop_index('ix_events_club_created', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_club_settings_club_id'), table_name='club_settings')
    op.drop_table('club_settings')
    op.drop_index('ix_admin_clubs_club_id', table_name='admin_clubs')
    op.drop_index('ix_admin_clubs_admin_id', table_name='admin_clubs')
    op.drop_table('admin_clubs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_djs_telegram_id'), table_name='djs')
    op.drop_index('ix_djs_name', table_name='djs')
    op.drop_table('djs')
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.drop_index('ix_clubs_name', table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_telegram_id'), table_name='admin_users')
    op.drop_index('ix_admin_users_is_active', table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
