"""Update

Revision ID: 37384075330c
Revises: 5282e4eead3d
Create Date: 2025-10-13 14:37:26.465534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37384075330c'
down_revision: Union[str, Sequence[str], None] = '5282e4eead3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_start_date_title'), table_name='events')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_djs_id'), table_name='djs')
    op.drop_index(op.f('ix_djs_telegram_id'), table_name='djs')
    op.drop_table('djs')
    op.drop_index(op.f('ix_organisators_id'), table_name='organisators')
    op.drop_table('organisators')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisators',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('organisators_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organisators_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_organisators_id'), 'organisators', ['id'], unique=False)
    op.create_table('djs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('djs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='djs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_djs_telegram_id'), 'djs', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_djs_id'), 'djs', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preview', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organisator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dj_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], name=op.f('events_dj_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisator_id'], ['organisators.id'], name=op.f('events_organisator_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_index(op.f('ix_events_start_date_title'), 'events', ['start_date', 'title'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###
